### ISSUE TITLE
Test input data

### ISSUE THREAD

**Issue by StockDrivenAI** [ZhengChang467/STRPM#4]
First, thank you for your code. 
Could you share the whole processed(decoded) test set or how to pre-process the videos and train-test split file ?
Especially for the SJTU4K and UCF

**Comment by ZhengChang467** [comment]
Thanks for your attention to our work. The processing code has been provided in core/data_provider/ucfsport.py, and the train-test split file has been provided in datasets/ucfsports. We plan to share the train-test split file of other datasets soon.

**Comment by StockDrivenAI** [comment]
Thanks !
